#!/usr/bin/env python3
"""Generate the monochrome turbine's native NeoForge OBJ assets (stdlib only)."""
from pathlib import Path
import json
import math
import struct
import zlib

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'src/main/resources/assets/waterturbine'
MODELS = ASSETS / 'models/block'
TAU = math.tau


def sub(a, b):
    return tuple(x-y for x, y in zip(a, b))


def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])


class Mesh:
    def __init__(self):
        self.faces = []

    def face(self, vertices, material, outward):
        points = []
        for p in vertices:
            if not any(sum((a-b)**2 for a, b in zip(p, q)) < 1e-16 for q in points):
                points.append(p)
        if len(points) < 3:
            return
        n = cross(sub(points[1], points[0]), sub(points[2], points[0]))
        if sum(a*b for a, b in zip(n, outward)) < 0:
            points.reverse()
            n = tuple(-x for x in n)
        length = math.sqrt(sum(x*x for x in n))
        if length < 1e-12:
            return
        self.faces.append((points, material, tuple(x/length for x in n)))

    def lathe(self, profile, material, sides=24):
        for (z1, r1), (z2, r2) in zip(profile, profile[1:]):
            for i in range(sides):
                a, b = i*TAU/sides, (i+1)*TAU/sides
                points = [(0.5+r*math.cos(t), 0.5+r*math.sin(t), z)
                          for z, r, t in [(z1,r1,a),(z1,r1,b),(z2,r2,b),(z2,r2,a)]]
                self.face(points, material, ((z2-z1)*math.cos((a+b)/2),
                                            (z2-z1)*math.sin((a+b)/2), r1-r2))

    def ring(self, z, radius, thickness, material):
        self.lathe([(z+thickness*math.sin(i*TAU/8), radius+thickness*math.cos(i*TAU/8))
                    for i in range(9)], material)

    def box(self, lo, hi, material):
        x,y,z = lo; X,Y,Z = hi
        for points, normal in [
            ([(x,y,z),(x,Y,z),(x,Y,Z),(x,y,Z)],(-1,0,0)),
            ([(X,y,z),(X,Y,z),(X,Y,Z),(X,y,Z)],(1,0,0)),
            ([(x,y,z),(X,y,z),(X,y,Z),(x,y,Z)],(0,-1,0)),
            ([(x,Y,z),(X,Y,z),(X,Y,Z),(x,Y,Z)],(0,1,0)),
            ([(x,y,z),(X,y,z),(X,Y,z),(x,Y,z)],(0,0,-1)),
            ([(x,y,Z),(X,y,Z),(X,Y,Z),(x,Y,Z)],(0,0,1))]:
            self.face(points, material, normal)

    def ellipsoid(self, center, scale, material):
        def point(a,b):
            return (center[0]+scale[0]*math.sin(a)*math.cos(b),
                    center[1]+scale[1]*math.cos(a),
                    center[2]+scale[2]*math.sin(a)*math.sin(b))
        for i in range(8):
            for j in range(16):
                ps=[point(a*math.pi/8,b*TAU/16) for a,b in [(i,j),(i+1,j),(i+1,j+1),(i,j+1)]]
                mean=tuple(sum(p[k] for p in ps)/4-center[k] for k in range(3))
                self.face(ps,material,mean)

    def save(self, name):
        lines=['# Generated by tools/generate_turbine_assets.py',
               'mtllib waterturbine:models/block/turbine.mtl',
               'vt 0.25 0.25','vt 0.75 0.25','vt 0.75 0.75','vt 0.25 0.75']
        vertex=1
        for normal_index,(points,material,normal) in enumerate(self.faces,1):
            lines.append('usemtl '+material)
            for p in points:
                lines.append('v '+' '.join(f'{v:.6f}' for v in p))
            lines.append('vn '+' '.join(f'{v:.6f}' for v in normal))
            lines.append('f '+' '.join(f'{vertex+i}/{i+1}/{normal_index}' for i in range(len(points))))
            vertex+=len(points)
        (MODELS/(name+'.obj')).write_text('\n'.join(lines)+'\n')


def png(path, rgb):
    # Small opaque texture, keeping the model in the standard block atlas.
    def chunk(name, data):
        return struct.pack('>I',len(data))+name+data+struct.pack('>I',zlib.crc32(name+data)&0xffffffff)
    pixels=b''.join(b'\x00'+bytes(rgb)*16 for _ in range(16))
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_bytes(b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',16,16,8,2,0,0,0))+
                     chunk(b'IDAT',zlib.compress(pixels))+chunk(b'IEND',b''))


def model(name):
    return {'parent':'minecraft:block/block','loader':'neoforge:obj',
            'model':f'waterturbine:models/block/{name}.obj','automatic_culling':False,
            'shade_quads':True,'emissive_ambient':False,
            'textures':{'particle':'waterturbine:block/turbine_white'}}


def write_json(path, data):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(data,indent=2)+'\n')


def main():
    MODELS.mkdir(parents=True,exist_ok=True)
    palette={'white':(232,234,233),'black':(27,29,31),'silver':(137,143,147)}
    for name,rgb in palette.items():
        png(ASSETS/f'textures/block/turbine_{name}.png',rgb)
    (MODELS/'turbine.mtl').write_text('\n'.join(
        f'newmtl {name}\nKd 1 1 1\nmap_Kd waterturbine:block/turbine_{name}\n' for name in palette))

    body=Mesh()
    body.lathe([(.16,0),(.16,.145),(.22,.195),(.3,.225),(.5,.225),(.61,.19),(.67,.125),(.67,0)],'white')
    # North-facing outlet: a hollow lip, dark interior, and white center vanes.
    body.lathe([(.075,.11),(.075,.14),(.18,.16),(.18,.12),(.075,.11)],'black')
    body.ring(.075,.132,.014,'white')
    body.ring(.19,.166,.012,'black')
    body.lathe([(.14,0),(.14,.113)],'black')
    body.box((.493,.39,.103),(.507,.61,.12),'silver')
    body.box((.39,.493,.103),(.61,.507,.12),'silver')
    body.lathe([(.097,0),(.097,.032),(.14,.032)],'white')
    body.ring(.63,.17,.013,'black')
    body.lathe([(.65,.056),(.83,.056)],'silver')
    body.lathe([(.65,.08),(.71,.08)],'black')
    for sign in [-1,1]:
        body.ellipsoid((.5+sign*.211,.49,.4),(.024,.077,.158),'black')
        body.ellipsoid((.5+sign*.155,.647,.4),(.052,.036,.12),'white')
        for i in range(4):
            x=.5+sign*.235
            body.box((x-.005,.465,.32+i*.037),(x+.005,.51,.329+i*.037),'silver')
        x=.5+sign*.23
        body.box((x-.006,.482,.49),(x+.006,.499,.526),'white')
    body.box((.405,.24,.32),(.595,.305,.49),'black')
    body.box((.43,.14,.345),(.57,.24,.465),'white')
    body.box((.39,.125,.315),(.61,.15,.495),'black')

    rotor=Mesh()
    rotor.lathe([(.78,0),(.78,.09),(.87,.1),(.94,.055),(.95,0)],'white')
    rotor.ring(.81,.09,.011,'black')
    for k in range(4):
        material='white' if k%2==0 else 'black'
        strips=[]
        for j in range(13):
            u=j/12;radius=.075+.35*u;angle=k*TAU/4+u*1.08
            width=.14+.16*math.sin(u*math.pi)
            strips.append([(.5+radius*math.cos(angle+side*width),
                            .5+radius*math.sin(angle+side*width),.835+.052*u+side*.022)
                           for side in [-1,1]])
        for a,b in zip(strips,strips[1:]):
            front=[a[0],b[0],b[1],a[1]]
            back=[(x,y,z+.014) for x,y,z in front]
            rotor.face(front,material,(0,0,-1));rotor.face(back,material,(0,0,1))
            for edge in [0,1]:
                ps=[a[edge],b[edge],tuple(v+(0.014 if i==2 else 0) for i,v in enumerate(b[edge])),
                    tuple(v+(0.014 if i==2 else 0) for i,v in enumerate(a[edge]))]
                n=cross(sub(ps[1],ps[0]),sub(ps[2],ps[0]))
                if edge==0:n=tuple(-v for v in n)
                rotor.face(ps,'silver',n)
        for strip,sign in [(strips[0],-1),(strips[-1],1)]:
            a,b=strip
            ps=[a,b,(b[0],b[1],b[2]+.014),(a[0],a[1],a[2]+.014)]
            rotor.face(ps,'silver',(sign*(a[0]-.5),sign*(a[1]-.5),0))
    body.save('turbine_body');rotor.save('turbine_rotor')
    item=Mesh();item.faces=body.faces+rotor.faces;item.save('turbine_complete')
    write_json(MODELS/'water_turbine.json',model('turbine_body'))
    write_json(MODELS/'turbine_rotor.json',model('turbine_rotor'))
    inventory=model('turbine_complete')
    inventory['display']={'gui':{'rotation':[25,135,0],'translation':[0,0,0],'scale':[.85,.85,.85]},
                          'fixed':{'rotation':[0,180,0],'translation':[0,0,0],'scale':[.8,.8,.8]}}
    write_json(ASSETS/'models/item/water_turbine.json',inventory)
    write_json(ASSETS/'blockstates/water_turbine.json',{'variants':{
        f'facing={direction},waterlogged={wet}':dict(model='waterturbine:block/water_turbine',**({'y':angle} if angle else {}))
        for direction,angle in [('north',0),('east',90),('south',180),('west',270)]
        for wet in ['false','true']}})
    print(f'Generated body {len(body.faces)} faces, rotor {len(rotor.faces)} faces; inventory includes both.')


if __name__=='__main__':
    main()
